language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

sudo: true

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-add-repository
                                                                    universe; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install
                                                           libiomp-dev --yes; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew search omp; fi
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libiomp; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade cmake; fi

sudo: false

before_script:
  - cmake --version
  - cd ..
  - git clone https://github.com/ISCDtoolbox/Commons.git
  - cd Commons
  - git branch test_future_update
  - git checkout test_future_update
  - git pull origin test_future_update 
  - mkdir build
  - cd build
  - cmake .. -DOPENMP=1
  - head CMakeFiles/Commons.dir/flags.make
  - head CMakeFiles/Commons.dir/link.txt
  - make
  - make install
  - cd ../../Mshdist

script:
  - mkdir build
  - cd build
  - cmake ..
  - head CMakeFiles/Mshdistance.dir/flags.make
  - head CMakeFiles/Mshdistance.dir/link.txt
  - head CMakeFiles/mshdist.dir/flags.make
  - head CMakeFiles/mshdist.dir/link.txt
  - make
  - make install
  - mshdist ../documentation/Examples/batkeep.mesh -ncpu 4

notifications:
  email: false

