language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libomp ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade cmake  ; fi

sudo: false

before_script:
  - cmake --version
  - git clone https://github.com/ISCDtoolbox/Commons.git
  - cd Commons
  - mkdir build
  - cd build
  - cmake .. -DOPENMP=1
  - head CMakeFiles/Commons.dir/flags.make
  - head CMakeFiles/Commons.dir/link.txt
  - make
  - make install
  - cd ../../Mshdist

script:
  - mkdir build
  - cd build
  - cmake ..
  - head CMakeFiles/Commons.dir/flags.make
  - head CMakeFiles/Commons.dir/link.txt
  - make
  - make install
  - mshdist -?

notifications:
  email: false

