language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then
                    sudo updatedb ; else sudo /usr/libexec/locate.updatedb ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then
        locate libc.so libm.so libpthread.so libgomp.so libomp.so libiomp5.so ;
            else locate libc.dylib libm.dylib libpthread.dylib libgomp.dylib
                                               libiomp5.dylib libomp.dylib ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then
         sudo apt-get install libiomp-dev --yes ; else brew install libomp ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then brew upgrade cmake ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then brew install valgrind ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then
                    sudo updatedb ; else sudo /usr/libexec/locate.updatedb ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then
        locate libc.so libm.so libpthread.so libgomp.so libomp.so libiomp5.so ;
            else locate libc.dylib libm.dylib libpthread.dylib libgomp.dylib
                                               libiomp5.dylib libomp.dylib ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then
                                             lsb_release -a ; else sw_vers ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then lscpu ; else sysctl hw ; fi
  - if [[ "$TRAVIS_COMPILER" == "gcc" ]] ; then
                                      gcc --version ; else clang --version ; fi
  - git --version
  - make --version
  - cmake --version

sudo: false

script:
  - cd ..
  - git clone https://github.com/ISCDtoolbox/Commons.git
  - cd Commons
  - git branch test_future_update
  - git checkout test_future_update
  - git pull origin test_future_update
  - mkdir build
  - cd build
  - cmake ..
  - head CMakeFiles/Commons.dir/flags.make
  - head CMakeFiles/Commons.dir/link.txt
  - make
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then
                        ldd libCommons.so ; else otool -L libCommons.dylib ; fi
  - make install
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then ldd ~/lib/iscd/libCommons.so ;
                                 else otool -L ~/lib/iscd/libCommons.dylib ; fi
  - cd ../../Mshdist
  - mkdir build
  - cd build
  - cmake ..
  - head CMakeFiles/Mshdistance.dir/flags.make
  - head CMakeFiles/Mshdistance.dir/link.txt
  - head CMakeFiles/mshdist.dir/flags.make
  - head CMakeFiles/mshdist.dir/link.txt
  - make
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then
                     ldd libMshdistance.a ; else otool -L libMshdistance.a ; fi
  - make install
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ;
                 then ldd ~/lib/iscd/libMshdistance.a ;
                                 else otool -L ~/lib/iscd/libMshdistance.a ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then
        valgrind mshdist ../documentation/Examples/saddle3d.mesh -dom -ncpu 1 ;
         else mshdist ../documentation/Examples/saddle3d.mesh -dom -ncpu 1 ; fi
  - rm ../documentation/Examples/saddle3d.sol
  - mshdist ../documentation/Examples/saddle3d.mesh -dom -ncpu 2
  - rm ../documentation/Examples/saddle3d.sol
  - cd ../../Commons/build
  - rm -r ./*
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_COMPILER" == "clang" ]] ;
         then cmake .. -DOPENMP=1 -DFORCEIOMP=1 ; else cmake .. -DOPENMP=1 ; fi
  - head CMakeFiles/Commons.dir/flags.make
  - head CMakeFiles/Commons.dir/link.txt
  - make
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then
                        ldd libCommons.so ; else otool -L libCommons.dylib ; fi
  - make install
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then ldd ~/lib/iscd/libCommons.so ;
                                 else otool -L ~/lib/iscd/libCommons.dylib ; fi
  - cd ../../Mshdist/build
  - rm -r ./*
  - cmake ..
  - head CMakeFiles/Mshdistance.dir/flags.make
  - head CMakeFiles/Mshdistance.dir/link.txt
  - head CMakeFiles/mshdist.dir/flags.make
  - head CMakeFiles/mshdist.dir/link.txt
  - make
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then
                     ldd libMshdistance.a ; else otool -L libMshdistance.a ; fi
  - make install
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ;
                 then ldd ~/lib/iscd/libMshdistance.a ;
                                 else otool -L ~/lib/iscd/libMshdistance.a ; fi
  - mshdist ../documentation/Examples/saddle3d.mesh -dom -ncpu 1
  - rm ../documentation/Examples/saddle3d.sol
  - mshdist ../documentation/Examples/saddle3d.mesh -dom -ncpu 2
  - rm ../documentation/Examples/saddle3d.sol

notifications:
  email: false

